services:
  - type: web
    name: crypto-server
    env: python
    plan: free
    startCommand: sh build.sh
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: "true"
